MODULE    = drc
MAGICDIR  = ..
SRCS      = DRCarray.c DRCbasic.c DRCcif.c DRCcontin.c DRCmain.c \
	    DRCsubcell.c DRCtech.c DRCprint.c DRCextend.c

include ${MAGICDIR}/defs.mak
include ${MAGICDIR}/rules.mak
