MODULE   =  cif
MAGICDIR =  ..
SRCS     =  CIFgen.c CIFhier.c CIFmain.c CIFrdcl.c CIFrdpt.c CIFrdpoly.c \
            CIFrdtech.c CIFrdutils.c CIFsee.c CIFtech.c CIFwrite.c

include ${MAGICDIR}/defs.mak
include ${MAGICDIR}/rules.mak
