MODULE    = extract
MAGICDIR  = ..
SRCS      = ExtArray.c ExtBasic.c ExtCell.c ExtCouple.c ExtHard.c \
            ExtHier.c ExtLength.c ExtMain.c ExtNghbors.c ExtPerim.c \
            ExtRegion.c ExtSubtree.c ExtTech.c ExtTest.c ExtTimes.c ExtYank.c \
            ExtInter.c ExtUnique.c 

include ${MAGICDIR}/defs.mak
include ${MAGICDIR}/rules.mak
