MODULE    = netmenu
MAGICDIR  = ..
SRCS      = NMbutton.c NMcmdAK.c NMcmdLZ.c NMlabel.c NMmain.c \
            NMnetlist.c NMshowpt.c NMshowcell.c NMundo.c NMwiring.c 

include ${MAGICDIR}/defs.mak
include ${MAGICDIR}/rules.mak
